spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dawid97/microservices-config-server
          username:
          password:
          clone-on-start: true

server:
  port: 8888